---

- name: Ensure docker packages are installed.
  yum: "name={{ item }} state=installed  update_cache=yes"
  with_items: 
    - lvm2
    - yum-utils
    - device-mapper-persistent-data

- name: Install docker repo.
  shell: "yum-config-manager --add-repo https://mirrors.ustc.edu.cn/docker-ce/linux/centos/docker-ce.repo"

- name: Modify the docker software source for keda.
  replace:
    path: /etc/yum.repos.d/docker-ce.repo
    regexp: 'download\.docker\.com'
    replace: "mirrors.ustc.edu.cn/docker-ce"
    